global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
rule_files:
  - /etc/prometheus/alert_rules.yml
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: ping
    static_configs:
      - targets: [ 'ping:9427' ]
