apiVersion: 1
# Can only have one datasource with a password due to setEnv.sh.
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    uid: "PBFA97CFB590B2093"
